# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:               Buckeye Cocoa
email:               info@buckeyecocoa.org
description: > # this means to ignore newlines until "baseurl:"
  Buckeyecocoa is Central Ohio's User Group for Mac and iOS Software Development
tagline:              CBus Cocoa/Swift Mac/iOS Developers Group
url:                 http://buckeyecocoa.org
baseurl: "" # the subpath of your site, e.g. /blog
paginate: 1 # pagination based on number of posts
paginate_path: "page/:num"
#highlighter: pygments
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username:    buckeyecocoa
github_username:     buckeyecocoa
permalink:           pretty

# About/contact
author:
  name: Shane Zatezalo
  url:  http://lottadot.com 

# Build settings
markdown: kramdown

#theme: cayman
gems:
  - jekyll-feed
  - jekyll-paginate


# Exclusions
exclude:
  - Gemfile
  - Gemfile.lock
  - .DS_Store
  - _config.yml
  - .gitignore
  - LICENSE.md
  - README.md
  - s3_website.yml
  - .env
  - Rakefile
